# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme: "mmistakes/so-simple-theme"
remote_theme: "mmistakes/so-simple-theme"

# Site wide configuration

locale: en-US
title: "So Simple Development Site"
description: "data science side projects, thoughts & experiments"
baseurl: # the subpath of your site, e.g. "/blog"
url: "https://tuanavu.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/images/so-simple-site-logo.png" # path of site logo, e.g. "/assets/images/logo.png"
date_format: "%B %-d, %Y"
search: true
read_time: true # reading time estimates, e.g. true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
#url: http://localhost:4000
# url: http://tuanavu.github.io/blog

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
highlighter: rouge
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# # Jekyll configuration
# permalink: /:categories/:title/
# markdown: kramdown
# highlighter: rouge
# sass:
#   sass_dir: _sass
#   style: compressed
# gems:
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/


# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# kramdown:
#   input: GFM
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..3
#   enable_coderay: false

# Site Author
author:
  name: Michael Rose
  picture: /images/michael-rose-photo.jpg
  email:
  twitter: mmistakes
  links:
    - title: Twitter
      url: https://twitter.com/mmistakes
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/mmistakes
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/mmistakes
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/mmistakes
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/mmistakes
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/mmistakes
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# # Site owner
# owner:
#   name: Tuan Vu
#   avatar: bio-photo.jpg
#   email: tuanvu216@yahoo.com
#   disqus-shortname: tuanavu
#   twitter: TuanVu8
#   facebook: tuan.vu.37625
#   github: "tuanavu"
#   stackexchange:
#   linkedin:
#   instagram:
#   flickr:
#   tumblr: mademistakes
#   pinterest:
#   weibo:
#   google:
#     plus:
#     analytics: #UA-2011187-2
#     verify: #UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y
#     ad-client: #ca-pub-7328585512091257
#     ad-slot: #7855747535
#   bing-verify: