# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme                    : "mmistakes/so-simple-theme"
remote_theme             : "mmistakes/so-simple-theme"

# Site wide configuration

title: andrew brooks
locale: en_US
description: data science side projects, thoughts & experiments
logo: ab-logo.jpg
search: true
#url: http://localhost:4000
url: http://tuanavu.github.io/blog

# Jekyll configuration

permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true


# Site owner
owner:
  name: Tuan Vu
  avatar: bio-photo.jpg
  email: tuanvu216@yahoo.com
  disqus-shortname: tuanavu
  twitter: TuanVu8
  facebook: tuan.vu.37625
  github: "tuanavu"
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr: mademistakes
  pinterest:
  weibo:
  google:
    plus:
    analytics: #UA-2011187-2
    verify: #UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y
    ad-client: #ca-pub-7328585512091257
    ad-slot: #7855747535
  bing-verify: